#! /usr/bin/env python
# Copyright (C) 2009 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPLv3 or later

import sys
import xml.dom.minidom


def log(message):
	print >> sys.stderr, message

def print_usage():
	print >> sys.stderr, """\
USAGE
  svgstrip [-v|--verbose] [-p|--pretend] strip [[-i|--in-place] <filename>]

EXAMPLES
  svgstrip strip drawing.svg > stripped-drawing.svg
  svgstrip strip --in-place drawing.svg
"""


def set(settings, key, value):
	settings[key] = value
	return settings


def parse_command_line(params, settings):
	usage, error = (False, False)

	actions = {
		'--verbose': lambda x: set(x, "verbose", True),
		'--pretend': lambda x: set(x, "pretend", True),
		'--in-place': lambda x: set(x, "inplace", True),
	}
	actions["-v"] = actions["--verbose"]
	actions["-p"] = actions["--pretend"]
	actions["-i"] = actions["--in-place"]

	for v in params:
		try:
			settings = actions[v](settings)
		except KeyError:
			if settings["filename"] == None:
				settings["filename"] = v
			else:
				# More than one filename given
				error = True
				break

	if settings["filename"] == None:
		if settings["inplace"]:
			# Stdin and in-place don't mix well
			error = True
		else:
			settings["filename"] = '/dev/stdin'

	return (usage, error)


def run(settings):
	dom = xml.dom.minidom.parse(settings["filename"])
	root_node = dom.getElementsByTagName("svg")[0]
	for v in ('sodipodi:docname', 'inkscape:export-filename'):
		if root_node.hasAttribute(v):
			if not settings["pretend"]:
				root_node.removeAttribute(v)
			log("Attribute %s deleted" % v)
	
	output_filename = settings["inplace"] \
		and (settings["pretend"] \
			and '/dev/null' \
			or settings["filename"]) \
		or '/dev/stdout'
		
	dom.writexml(open(output_filename, 'w'))
	return 0


if __name__ == "__main__":
	settings = {
		"verbose":False,
		"pretend":False,
		"inplace":False,
		"filename":None,
	}

	usage, error = parse_command_line(sys.argv[1:], settings)
	if usage or error:
		print_usage()
		sys.exit(error and 1 or 0)
	else:
		sys.exit(run(settings))
